import{S as p,i as n}from"./assets/vendor-46aac873.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const i of e.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerpolicy&&(e.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?e.credentials="include":t.crossorigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(t){if(t.ep)return;t.ep=!0;const e=a(t);fetch(t.href,e)}})();const u=document.querySelector(".form"),c=document.querySelector(".gallery"),f=document.querySelector(".loader"),l={key:"41869346-1dc68e1b0e88fdca1b815defb",q:"black",image_type:"photo",orientation:"horizontal",safesearch:!0},m=new p(".gallery a",{captionsData:"alt",captionDelay:250});async function d(s){try{const r=await fetch(`https://pixabay.com/api/?${s}`);if(!r.ok)throw new Error(r.statusText);const{hits:a}=await r.json();if(a.length>0){const o=a.reduce((t,e)=>t+`<li class="gallery-item">
        <a href=${e.largeImageURL}> 
          <img class="gallery-link" src ='${e.webformatURL}' alt='${e.tags}' width='360' height='200'/>
        </a>
        <ul class='gallery-statistic'>
                  <li><p class='statistic'>💗 Likes<span>${e.likes}</span></p></li>
                  <li><p class='statistic'>👁️ Views<span>${e.views}</span></p></li>
                  <li><p class='statistic'>💬 Comments<span>${e.comments}</span></p></li>
                  <li><p class='statistic'>💌 Downloads<span>${e.downloads}</span></p></li>
              </ul>
      </li>`,"");c.innerHTML=o,m.refresh()}else n.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#ef4040",messageSize:"16px",messageColor:"#fafafb"})}catch{n.error({position:"topRight",message:"Sorry, there was an error fetching the data. Please try again!",backgroundColor:"#ef4040",messageSize:"16px",messageColor:"#fafafb"})}finally{f.style.display="none"}}u.addEventListener("submit",s=>{s.preventDefault(),c.innerHTML="",f.style.display="block",l.q=s.target.elements.search.value.trim();const r=new URLSearchParams(l);d(r),s.currentTarget.reset()});
//# sourceMappingURL=commonHelpers.js.map
